compact: true
directory:
- aws-hybrid-vpn-gcp
download-external-modules: true
evaluate-variables: true
external-modules-download-path: .terraform
quiet: true
skip-path:
  - .external_modules
  - modules
